In [1]:
!apt-get install openjdk-11-jdk -y

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  at-spi2-core fonts-dejavu-core fonts-dejavu-extra gsettings-desktop-schemas
  libatk-bridge2.0-0 libatk-wrapper-java libatk-wrapper-java-jni libatk1.0-0
  libatk1.0-data libatspi2.0-0 libxcomposite1 libxt-dev libxtst6 libxxf86dga1
  openjdk-11-jdk-headless openjdk-11-jre openjdk-11-jre-headless
  session-migration x11-utils
Suggested packages:
  libxt-doc openjdk-11-demo openjdk-11-source visualvm libnss-mdns
  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei
  | fonts-wqy-zenhei fonts-indic mesa-utils
The following NEW packages will be installed:
  at-spi2-core fonts-dejavu-core fonts-dejavu-extra gsettings-desktop-schemas
  libatk-bridge2.0-0 libatk-wrapper-java libatk-wrapper-java-jni libatk1.0-0
  libatk1.0-data libatspi2.0-0 libxcomposite1 libxt-dev libxtst6 libxxf86dga1
  openjdk-11-jdk openjdk-11-jdk-headless openjdk-11-jre
  openjdk-11-jre-headless session-migration x11-utils
0 upgraded, 20 newly installed, 0 to remove and 41 not upgraded.
Need to get 122 MB of archives.
After this operation, 275 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-core all 2.37-2build1 [1,041 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-extra all 2.37-2build1 [2,041 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86dga1 amd64 2:1.1.5-0ubuntu3 [12.6 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 x11-utils amd64 7.7+5build2 [206 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java all 0.38.0-5build1 [53.1 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java-jni amd64 0.38.0-5build1 [49.0 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxt-dev amd64 1:1.2.1-1 [396 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jre-headless amd64 11.0.28+6-1ubuntu1~22.04.1 [42.6 MB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jre amd64 11.0.28+6-1ubuntu1~22.04.1 [214 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.28+6-1ubuntu1~22.04.1 [73.6 MB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk amd64 11.0.28+6-1ubuntu1~22.04.1 [1,342 kB]
Fetched 122 MB in 6s (21.6 MB/s)
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 121703 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package fonts-dejavu-core.
Preparing to unpack .../05-fonts-dejavu-core_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-core (2.37-2build1) ...
Selecting previously unselected package fonts-dejavu-extra.
Preparing to unpack .../06-fonts-dejavu-extra_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-extra (2.37-2build1) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../07-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../08-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../09-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../10-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../11-libxxf86dga1_2%3a1.1.5-0ubuntu3_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../12-x11-utils_7.7+5build2_amd64.deb ...
Unpacking x11-utils (7.7+5build2) ...
Selecting previously unselected package libatk-wrapper-java.
Preparing to unpack .../13-libatk-wrapper-java_0.38.0-5build1_all.deb ...
Unpacking libatk-wrapper-java (0.38.0-5build1) ...
Selecting previously unselected package libatk-wrapper-java-jni:amd64.
Preparing to unpack .../14-libatk-wrapper-java-jni_0.38.0-5build1_amd64.deb ...
Unpacking libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Selecting previously unselected package libxt-dev:amd64.
Preparing to unpack .../15-libxt-dev_1%3a1.2.1-1_amd64.deb ...
Unpacking libxt-dev:amd64 (1:1.2.1-1) ...
Selecting previously unselected package openjdk-11-jre-headless:amd64.
Preparing to unpack .../16-openjdk-11-jre-headless_11.0.28+6-1ubuntu1~22.04.1_amd64.deb ...
Unpacking openjdk-11-jre-headless:amd64 (11.0.28+6-1ubuntu1~22.04.1) ...
Selecting previously unselected package openjdk-11-jre:amd64.
Preparing to unpack .../17-openjdk-11-jre_11.0.28+6-1ubuntu1~22.04.1_amd64.deb ...
Unpacking openjdk-11-jre:amd64 (11.0.28+6-1ubuntu1~22.04.1) ...
Selecting previously unselected package openjdk-11-jdk-headless:amd64.
Preparing to unpack .../18-openjdk-11-jdk-headless_11.0.28+6-1ubuntu1~22.04.1_amd64.deb ...
Unpacking openjdk-11-jdk-headless:amd64 (11.0.28+6-1ubuntu1~22.04.1) ...
Selecting previously unselected package openjdk-11-jdk:amd64.
Preparing to unpack .../19-openjdk-11-jdk_11.0.28+6-1ubuntu1~22.04.1_amd64.deb ...
Unpacking openjdk-11-jdk:amd64 (11.0.28+6-1ubuntu1~22.04.1) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up openjdk-11-jre-headless:amd64 (11.0.28+6-1ubuntu1~22.04.1) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
Setting up libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Setting up openjdk-11-jre:amd64 (11.0.28+6-1ubuntu1~22.04.1) ...
Setting up openjdk-11-jdk-headless:amd64 (11.0.28+6-1ubuntu1~22.04.1) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmic to provide /usr/bin/rmic (rmic) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jaotc to provide /usr/bin/jaotc (jaotc) in auto mode
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libxt-dev:amd64 (1:1.2.1-1) ...
Setting up fonts-dejavu-core (2.37-2build1) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up fonts-dejavu-extra (2.37-2build1) ...
Setting up openjdk-11-jdk:amd64 (11.0.28+6-1ubuntu1~22.04.1) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up x11-utils (7.7+5build2) ...
Setting up libatk-wrapper-java (0.38.0-5build1) ...
Setting up libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.6) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Setting up at-spi2-core (2.44.0-3) ...

In [1]:
! pip install johnsnowlabs

Requirement already satisfied: johnsnowlabs in /usr/local/lib/python3.12/dist-packages (6.2.0)
Requirement already satisfied: pyspark==3.4.0 in /usr/local/lib/python3.12/dist-packages (from johnsnowlabs) (3.4.0)
Requirement already satisfied: spark-nlp==6.2.0 in /usr/local/lib/python3.12/dist-packages (from johnsnowlabs) (6.2.0)
Requirement already satisfied: nlu==5.4.1 in /usr/local/lib/python3.12/dist-packages (from johnsnowlabs) (5.4.1)
Requirement already satisfied: spark-nlp-display==5.0 in /usr/local/lib/python3.12/dist-packages (from johnsnowlabs) (5.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from johnsnowlabs) (2.0.2)
Requirement already satisfied: dataclasses in /usr/local/lib/python3.12/dist-packages (from johnsnowlabs) (0.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from johnsnowlabs) (2.32.4)
Requirement already satisfied: databricks-api in /usr/local/lib/python3.12/dist-packages (from johnsnowlabs) (0.9.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.12/dist-packages (from johnsnowlabs) (2.11.10)
Requirement already satisfied: colorama in /usr/local/lib/python3.12/dist-packages (from johnsnowlabs) (0.4.6)
Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (from johnsnowlabs) (1.40.73)
Requirement already satisfied: pyarrow>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from nlu==5.4.1->johnsnowlabs) (18.1.0)
Requirement already satisfied: pandas>=1.3.5 in /usr/local/lib/python3.12/dist-packages (from nlu==5.4.1->johnsnowlabs) (2.2.2)
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.12/dist-packages (from pyspark==3.4.0->johnsnowlabs) (0.10.9.7)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from spark-nlp-display==5.0->johnsnowlabs) (7.34.0)
Requirement already satisfied: svgwrite==1.4 in /usr/local/lib/python3.12/dist-packages (from spark-nlp-display==5.0->johnsnowlabs) (1.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->johnsnowlabs) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->johnsnowlabs) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->johnsnowlabs) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->johnsnowlabs) (0.4.2)
Requirement already satisfied: botocore<1.41.0,>=1.40.73 in /usr/local/lib/python3.12/dist-packages (from boto3->johnsnowlabs) (1.40.73)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3->johnsnowlabs) (1.0.1)
Requirement already satisfied: s3transfer<0.15.0,>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from boto3->johnsnowlabs) (0.14.0)
Requirement already satisfied: databricks-cli in /usr/local/lib/python3.12/dist-packages (from databricks-api->johnsnowlabs) (0.18.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->johnsnowlabs) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->johnsnowlabs) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->johnsnowlabs) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->johnsnowlabs) (2025.10.5)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<1.41.0,>=1.40.73->boto3->johnsnowlabs) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->nlu==5.4.1->johnsnowlabs) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->nlu==5.4.1->johnsnowlabs) (2025.2)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from databricks-cli->databricks-api->johnsnowlabs) (8.3.0)
Requirement already satisfied: pyjwt>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from databricks-cli->databricks-api->johnsnowlabs) (2.10.1)
Requirement already satisfied: oauthlib>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from databricks-cli->databricks-api->johnsnowlabs) (3.3.1)
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.12/dist-packages (from databricks-cli->databricks-api->johnsnowlabs) (0.9.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from databricks-cli->databricks-api->johnsnowlabs) (1.17.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->spark-nlp-display==5.0->johnsnowlabs) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython->spark-nlp-display==5.0->johnsnowlabs) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->spark-nlp-display==5.0->johnsnowlabs) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->spark-nlp-display==5.0->johnsnowlabs) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->spark-nlp-display==5.0->johnsnowlabs) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->spark-nlp-display==5.0->johnsnowlabs) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->spark-nlp-display==5.0->johnsnowlabs) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->spark-nlp-display==5.0->johnsnowlabs) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->spark-nlp-display==5.0->johnsnowlabs) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->spark-nlp-display==5.0->johnsnowlabs) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->spark-nlp-display==5.0->johnsnowlabs) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->spark-nlp-display==5.0->johnsnowlabs) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->spark-nlp-display==5.0->johnsnowlabs) (0.2.14)

In [2]:
! pip install bertopic openai datamapplot
! pip install datasets transformers sentence-transformers

Collecting bertopic
  Downloading bertopic-0.17.3-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (1.109.1)
Collecting datamapplot
  Downloading datamapplot-0.6.4-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.40)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.9.post2)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.1.2)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.1)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.11.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.12.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.11.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: colorcet in /usr/local/lib/python3.12/dist-packages (from datamapplot) (3.1.0)
Collecting colorspacious>=1.1 (from datamapplot)
  Downloading colorspacious-1.1.2-py2.py3-none-any.whl.metadata (3.6 kB)
Collecting dask<2025.0.1,>=2024.4.1 (from dask[complete]<2025.0.1,>=2024.4.1->datamapplot)
  Downloading dask-2024.12.1-py3-none-any.whl.metadata (3.7 kB)
Collecting datashader>=0.16 (from datamapplot)
  Downloading datashader-0.18.2-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from datamapplot) (6.5.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from datamapplot) (3.1.6)
Requirement already satisfied: matplotlib>=3.8 in /usr/local/lib/python3.12/dist-packages (from datamapplot) (3.10.0)
Requirement already satisfied: numba>=0.56 in /usr/local/lib/python3.12/dist-packages (from datamapplot) (0.60.0)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (from datamapplot) (18.1.0)
Collecting pylabeladjust (from datamapplot)
  Downloading pylabeladjust-0.1.13-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from datamapplot) (2.32.4)
Collecting rcssmin>=1.1.2 (from datamapplot)
  Downloading rcssmin-1.2.2-cp312-cp312-manylinux1_x86_64.whl.metadata (4.8 kB)
Collecting rjsmin>=1.2.2 (from datamapplot)
  Downloading rjsmin-1.2.5-cp312-cp312-manylinux1_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: scikit-image>=0.22 in /usr/local/lib/python3.12/dist-packages (from datamapplot) (0.25.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from datamapplot) (4.5.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (8.3.0)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (25.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (6.0.3)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (0.12.1)
Collecting lz4>=4.3.2 (from dask[complete]<2025.0.1,>=2024.4.1->datamapplot)
  Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: multipledispatch in /usr/local/lib/python3.12/dist-packages (from datashader>=0.16->datamapplot) (1.0.0)
Requirement already satisfied: param in /usr/local/lib/python3.12/dist-packages (from datashader>=0.16->datamapplot) (2.2.1)
Collecting pyct (from datashader>=0.16->datamapplot)
  Downloading pyct-0.6.0-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from datashader>=0.16->datamapplot) (1.16.3)
Requirement already satisfied: xarray in /usr/local/lib/python3.12/dist-packages (from datashader>=0.16->datamapplot) (2025.10.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->datamapplot) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->datamapplot) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->datamapplot) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->datamapplot) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->datamapplot) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->datamapplot) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->datamapplot) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (8.5.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.22->datamapplot) (3.5)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.22->datamapplot) (2.37.2)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.22->datamapplot) (2025.10.16)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.22->datamapplot) (0.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.57.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.8.0+cu126)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.36.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->datamapplot) (3.0.3)
Collecting Pyqtree<2.0.0,>=1.0.0 (from pylabeladjust->datamapplot)
  Downloading Pyqtree-1.0.0.tar.gz (5.2 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->datamapplot) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->datamapplot) (2.5.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.20.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.2.0)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.8->datamapplot) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.3)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.4.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.6.2)
Collecting dask-expr<1.2,>=1.1 (from dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot)
  Downloading dask_expr-1.1.21-py3-none-any.whl.metadata (2.6 kB)
Collecting distributed==2024.12.1 (from dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot)
  Downloading distributed-2024.12.1-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: bokeh>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (3.7.3)
Requirement already satisfied: msgpack>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from distributed==2024.12.1->dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (1.1.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2024.12.1->dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (5.9.5)
Requirement already satisfied: sortedcontainers>=2.0.5 in /usr/local/lib/python3.12/dist-packages (from distributed==2024.12.1->dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2024.12.1->dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (3.2.1)
Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2024.12.1->dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (6.5.1)
Requirement already satisfied: zict>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2024.12.1->dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (3.0.0)
Requirement already satisfied: narwhals>=1.13 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1.0->dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (2.11.0)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1.0->dask<2025.0.1,>=2024.4.1->dask[complete]<2025.0.1,>=2024.4.1->datamapplot) (2025.10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Downloading bertopic-0.17.3-py3-none-any.whl (153 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.0/153.0 kB 8.3 MB/s eta 0:00:00
Downloading datamapplot-0.6.4-py3-none-any.whl (168 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.5/168.5 kB 16.9 MB/s eta 0:00:00
Downloading colorspacious-1.1.2-py2.py3-none-any.whl (37 kB)
Downloading dask-2024.12.1-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 49.1 MB/s eta 0:00:00
Downloading datashader-0.18.2-py3-none-any.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 118.8 MB/s eta 0:00:00
Downloading rcssmin-1.2.2-cp312-cp312-manylinux1_x86_64.whl (49 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 4.9 MB/s eta 0:00:00
Downloading rjsmin-1.2.5-cp312-cp312-manylinux1_x86_64.whl (31 kB)
Downloading pylabeladjust-0.1.13-py3-none-any.whl (19 kB)
Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 85.1 MB/s eta 0:00:00
Downloading distributed-2024.12.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 72.3 MB/s eta 0:00:00
Downloading pyct-0.6.0-py3-none-any.whl (16 kB)
Downloading dask_expr-1.1.21-py3-none-any.whl (244 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.3/244.3 kB 26.0 MB/s eta 0:00:00
Building wheels for collected packages: Pyqtree
  Building wheel for Pyqtree (setup.py) ... done
  Created wheel for Pyqtree: filename=Pyqtree-1.0.0-py3-none-any.whl size=5969 sha256=cadaab59486d6c999f8bbb1d50de21e1cb6021db96f723c9e3d77a236e3b5155
  Stored in directory: /root/.cache/pip/wheels/86/02/24/506ac193949f48c8bec599b613d722bd64a83063a190b3bff7
Successfully built Pyqtree
Installing collected packages: rjsmin, rcssmin, Pyqtree, pyct, lz4, colorspacious, dask, pylabeladjust, distributed, dask-expr, datashader, datamapplot, bertopic
  Attempting uninstall: dask
    Found existing installation: dask 2025.9.1
    Uninstalling dask-2025.9.1:
      Successfully uninstalled dask-2025.9.1
  Attempting uninstall: distributed
    Found existing installation: distributed 2025.9.1
    Uninstalling distributed-2025.9.1:
      Successfully uninstalled distributed-2025.9.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rapids-dask-dependency 25.10.0 requires dask==2025.9.1, but you have dask 2024.12.1 which is incompatible.
rapids-dask-dependency 25.10.0 requires distributed==2025.9.1, but you have distributed 2024.12.1 which is incompatible.
Successfully installed Pyqtree-1.0.0 bertopic-0.17.3 colorspacious-1.1.2 dask-2024.12.1 dask-expr-1.1.21 datamapplot-0.6.4 datashader-0.18.2 distributed-2024.12.1 lz4-4.4.5 pyct-0.6.0 pylabeladjust-0.1.13 rcssmin-1.2.2 rjsmin-1.2.5
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.1.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.20.0)

In [ ]:
#! pip install datasets

In [3]:
 ! pip install pyspark==3.5.1

Collecting pyspark==3.5.1
  Downloading pyspark-3.5.1.tar.gz (317.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.0/317.0 MB 4.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.12/dist-packages (from pyspark==3.5.1) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.1-py2.py3-none-any.whl size=317488493 sha256=65a619085bd668e021f8dd3e8da73da39ec7b32fb1309fa26188ba9001174a33
  Stored in directory: /root/.cache/pip/wheels/b1/91/5f/283b53010a8016a4ff1c4a1edd99bbe73afacb099645b5471b
Successfully built pyspark
Installing collected packages: pyspark
  Attempting uninstall: pyspark
    Found existing installation: pyspark 3.4.0
    Uninstalling pyspark-3.4.0:
      Successfully uninstalled pyspark-3.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
johnsnowlabs 6.2.0 requires pyspark==3.4.0, but you have pyspark 3.5.1 which is incompatible.
Successfully installed pyspark-3.5.1

This code initiates a spark session through spark-nlp and displays the version of Spark NLP and Spark that is currently running in our notebook.

In [4]:
import sparknlp
spark = sparknlp.start()

print("Spark NLP version: {}".format(sparknlp.version()))
print("Apache Spark version: {}".format(spark.version))

Spark NLP version: 6.2.0
Apache Spark version: 3.5.1

Here you will need to upload your dataset (reviews.csv) that you downloaded from http://insideairbnb.com/get-the-data/ and extracted. This dataset contains the actual reviews of the airbnb stays that we have referenced throughout the other homeworks this semester. Note: In this code I have connected my Google Drive but you may also just upload your file in the temp folders available in Google colab

In [5]:
reviewsDF = spark.read.options(mode='FAILFAST',
                               header= True, multiline = True, inferSchema=True, escape='"').csv('/content/reviews.csv.gz')

This code is something that I did to limit the amount of data that I was using from the dataset. This is to conserve on time sitting at the computer. The more data that you include in your model, the closer that your model will be to the actual topics but is more computationally expensive and will take a lot more time since we are running in a psuedo-spark environment and not an actual cluster computing scenario.

Make your choice about how accurate you want to be and how long you want to wait for the code to run.

In [6]:
### Split Dataset
(extraDF,useDF) = reviewsDF.randomSplit((0.60,0.40),seed=42)

A bit of data-engineering of assigning our text column to a variable name and cleaning out rows that are missing in the dataset.

In [7]:
from pyspark.sql import functions as F

text_col = 'comments'
review_text = useDF.select("listing_id","id",text_col).filter(F.col(text_col).isNotNull())

##ScreenShot #1 -
 Take a screen shot of the top 5 comments in your new dataset.

In [8]:
review_text.head(5)

[Row(listing_id=1913774, id=8865628, comments="Brian was an awesome host! The apartment was recently remodeled and definitely felt like a new home. I'd definitely stay here again. I love his place!"),
 Row(listing_id=1913774, id=9431986, comments='Brian was the absolute, best host.  If we needed anything he provided it. His studio is very sweet too.  The nine windows on three walls makes it feel very spacious.  It is decorated very tastefully.  Highly recommended!'),
 Row(listing_id=1913774, id=9915528, comments="great place! great view! easy to walk to everything! great, friendly, easy-to-communicate-with host! totally awesome dogs! i hope to be moving to bozeman, but if not and i'm just visiting i'd definitely want to stay there again. thanks, brian, for making it so easy!"),
 Row(listing_id=1913774, id=10386565, comments="My fiance and I had an absolutely amazing time staying at Brian's place in Bozeman!  The place is very clean, modern, and extremely comfortable!  We arrived to a bottle of wine, beer and water in the fridge, and warm coffee and tea any time we wanted it.  Brian was very friendly, welcoming, laid back, and helpful!  I cannot say enough good things about our stay here.  I think the number one way you can truly show how much you enjoyed a place is by using the same place to stay when you return to that city...and that is exactly what we'll be doing anytime we come to Bozeman!  We had plenty of privacy, and if we needed anything at all Brian was only a text or phone call away.  I HIGHLY RECOMMEND staying at this beautiful loft right next to downtown Bozeman."),
 Row(listing_id=1913774, id=10819586, comments='Brian was a a fantastic host. He was helpful with providing advice for places to go around town. The room was well equipped and exceptionally well put together. Would definitely stay here again.')]

In [12]:
review_text.show(5, truncate=False)

+----------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|listing_id|id      |comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+----------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|1913774   |8865628 |Brian was an awesome host! The apartment was recently remodeled and definitely felt like a new home. I'd definitely stay here again. I love his place!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|1913774   |9431986 |Brian was the absolute, best host.  If we needed anything he provided it. His studio is very sweet too.  The nine windows on three walls makes it feel very spacious.  It is decorated very tastefully.  Highly recommended!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|1913774   |9915528 |great place! great view! easy to walk to everything! great, friendly, easy-to-communicate-with host! totally awesome dogs! i hope to be moving to bozeman, but if not and i'm just visiting i'd definitely want to stay there again. thanks, brian, for making it so easy!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|1913774   |10386565|My fiance and I had an absolutely amazing time staying at Brian's place in Bozeman!  The place is very clean, modern, and extremely comfortable!  We arrived to a bottle of wine, beer and water in the fridge, and warm coffee and tea any time we wanted it.  Brian was very friendly, welcoming, laid back, and helpful!  I cannot say enough good things about our stay here.  I think the number one way you can truly show how much you enjoyed a place is by using the same place to stay when you return to that city...and that is exactly what we'll be doing anytime we come to Bozeman!  We had plenty of privacy, and if we needed anything at all Brian was only a text or phone call away.  I HIGHLY RECOMMEND staying at this beautiful loft right next to downtown Bozeman.|
|1913774   |10819586|Brian was a a fantastic host. He was helpful with providing advice for places to go around town. The room was well equipped and exceptionally well put together. Would definitely stay here again.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+----------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 5 rows


##BERTopic Modeling with HuggingFace (https://github.com/MaartenGr/BERTopic)

`from bertopic import BERTopic`

`topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    verbose=True
).fit(text, embeddings)`

BERTopic works rather straightforward. It consists of 5 sequential steps:

-

1.   Embedding documents
2.   Reducing the dimensionality of embeddings
3.   Cluster reduced embeddings
4.   Tokenize documents per cluster
5.   Extract best-representing words per cluster

https://colab.research.google.com/drive/1bxizKzv5vfxJEB29sntU__ZC7PBSIPaQ?usp=sharing#scrollTo=cadvhCBTc6Zz

#### Convert Dataset to HuggingFace with Datasets

# Convert each split to Hugging Face Dataset

Topic models could even be guided to see how many documents contain known potential topics in the corpus of documents... https://maartengr.github.io/BERTopic/getting_started/guided/guided.html

In [13]:
from datasets import *

reviews = Dataset.from_spark(review_text)
#from_spark is converting the pyspark dataframe to a hugging dataframe

####Embeddings (BERTopics uses Sentence Transformers)

(https://www.sbert.net/docs/sentence_transformer/pretrained_models.html)

Running embeddings before model. Typically, we want to iterate fast over different versions of our BERTopic model whilst we are trying to optimize it to a specific use case. To speed up this process, we can pre-compute the embeddings, save them, and pass them to BERTopic so it does not need to calculate the embeddings each time:

In [14]:
from sentence_transformers import SentenceTransformer

# Create an embedding for each abstract
embedding_model = SentenceTransformer('sentence-transformers/distilbert-base-nli-mean-tokens')
embeddings = embedding_model.encode(reviews['comments'], show_progress_bar=True)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/550 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/450 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/587 [00:00<?, ?it/s]




# BERTopics Model Pipeline Build

####UMAP (https://github.com/lmcinnes/umap)
`from umap import UMAP`

`umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42)`

UMAP is one of a few dimensionality reduction algorithms that keeps a significant portion of the high-dimensional local structure in lower dimensionality.

here are a number of parameters that can be set for the UMAP class; the major ones are as follows:

*  `n_neighbors`: This determines the number of neighboring points used in local approximations of manifold structure. Larger values will result in more global structure being preserved at the loss of detailed local structure. In general this parameter should often be in the range 5 to 50, with a choice of 10 to 15 being a sensible default.

*  `min_dist`: This controls how tightly the embedding is allowed compress points together. Larger values ensure embedded points are more evenly distributed, while smaller values allow the algorithm to optimise more accurately with regard to local structure. Sensible values are in the range 0.001 to 0.5, with 0.1 being a reasonable default.

*  `metric`: This determines the choice of metric used to measure distance in the input space. A wide variety of metrics are already coded, and a user defined function can be passed as long as it has been JITd by numba.


You can play around with the values of dimensionality to optimize for your topic creation. Note that too low dimensionality results in a loss of information while a too high dimensionality results in poorer clustering results.

In [16]:
from umap import UMAP
umap_model = UMAP(n_neighbors=12,
                  n_components=5,
                  min_dist=0.01,
                  metric='cosine',
                  random_state=42)

#### HDBSCAN (https://github.com/scikit-learn-contrib/hdbscan)

`from hdbscan import HDBSCAN`

`hdbscan_model = HDBSCAN(min_cluster_size=20, min_samples=2, metric='euclidean', cluster_selection_method='eom')`

Hierarchical Density-Based Spatial Clustering  of Applications with Noise (HDBSCAN). Performs DBSCAN over varying epsilon values and integrates the result to find a clustering that gives the best stability over epsilon. Used in transformer topic modeling after dimension reduction.

In [17]:
from hdbscan import HDBSCAN
hdbscan_model = HDBSCAN(min_cluster_size=20,
                        min_samples=2,
                        metric='euclidean',
                        cluster_selection_method='eom')

/usr/local/lib/python3.12/dist-packages/hdbscan/robust_single_linkage_.py:175: SyntaxWarning: invalid escape sequence '\{'
  $max \{ core_k(a), core_k(b), 1/\alpha d(a,b) \}$.

##Vectorizers

### CountVectorizer

Converts a collection of text documents to a matrix of token counts. You also have the ability to remove common words in english that do not carry much meaning ('stop words'). BERTopics works here with a sklearn package tool.

`from sklearn.feature_extraction.text import CountVectorizer`


###c-TF-IDF

In order to get an accurate representation of the topics from our bag-of-words matrix, TF-IDF was adjusted to work on a cluster/categorical/topic level instead of a document level. This adjusted TF-IDF representation is called c-TF-IDF and takes into account what makes the documents in one cluster different from documents in another cluster. This can also be used a type of filter in the construction of topics saying that we want to reduce the number of similar words in the topics.

`from bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer`

`ctfidf_model = ClassTfidfTransformer()
topic_model = BERTopic(ctfidf_model=ctfidf_model )`

There are two main options (which can be used together) -
- `bm25_weighting` is a boolean parameter that indicates whether a class-based BM-25 weighting measure is used instead of the default method as defined in the formula at the beginning of this page.
- `reduce_frequent_words` to take the square root of the term frequency after applying the weighting scheme.

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.vectorizers import ClassTfidfTransformer

vectorizer = CountVectorizer(stop_words="english")

#ctfidf
ctfidf_model = ClassTfidfTransformer(bm25_weighting=True,reduce_frequent_words=True)

In [19]:
from bertopic import BERTopic
from bertopic.representation import MaximalMarginalRelevance

representation_model = MaximalMarginalRelevance(diversity=0.2)
topic_model = BERTopic(representation_model=representation_model)

`nr_topics= ` This command lets you change the number of topics and 'auto' lets the system decide on the number of topics though this does not always produce the best results.

**CHANGE THE NUMBER OF TOPICS** from the number in this code and run the model a couple of times to see how your topics change with the different number of topics.

You can change the number of topics as you need to depending on the dataset and there are several methods and philopsophies on doing this. This is one of many packages that will evaluate topics (https://github.com/mind-Lab/octis)

In [20]:
# Train our topic model with BERTopic
from bertopic import BERTopic

topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer,
    nr_topics= 15,   # you could set this to 'auto' and it will assign the topics automatically
    ctfidf_model=ctfidf_model,
    representation_model=representation_model
).fit(reviews['comments'], embeddings)

##FULL MODEL IN ONE CELL (*Note: you do not need to run this cell if you have run the previous cells building the model* )

In [21]:
# Train our topic model with BERTopic limiting the number of topics
from bertopic import BERTopic
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.vectorizers import ClassTfidfTransformer


# Define sub-models
vectorizer = CountVectorizer(stop_words="english")
umap_model = UMAP(n_neighbors=10, min_dist=0.01, metric='cosine', random_state=42)
hdbscan_model = HDBSCAN(min_cluster_size=20, min_samples=2, metric='euclidean', cluster_selection_method='eom')
ctfidf_model = ClassTfidfTransformer(bm25_weighting=True,reduce_frequent_words=True)

topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer,
    nr_topics=28,
    ctfidf_model=ctfidf_model
).fit(reviews['comments'], embeddings)

#Screen Shot #2

###Model Output
`topic_model.get_topic(##)`

This command will allow us to see the topics that our run of the model has created. The output shows:

**Topic number** Numbering starts at -1 but this topic can mostly be ignored if it is not containing all of your count because of how the BERTopics model uses this -1 topic to store outliers in it's model.

**Count**  - count of topic occurence in the dataset


**Name ** model given name using the top three or four words in the topic


**Representation** - top ten words contributing to the topic


**Representative_Docs** - a single document ( a review in our use case) that is representative of the topic.

====

*Run the `topic_model.get_topic()` call and take a screenshot of the output produced.*

In [22]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,5249,-1_enjoyed_loved_stayed_cozy,"[enjoyed, loved, stayed, cozy, needed, town, t...",[Lark was very flexible and friendly. She was...
1,0,5768,0_coffee_kitchen_airbnb_loved,"[coffee, kitchen, airbnb, loved, walk, family,...",[This was our very first Airbnb reservation. ...
2,1,1299,1_helpful_responsive_host_communication,"[helpful, responsive, host, communication, acc...",[Such an amazing place to stay! Super clean an...
3,2,1218,2_distance_walkable_walking_quiet,"[distance, walkable, walking, quiet, restauran...",[This place is perfect for your Bozeman stay! ...
4,3,891,3_communication_convenient_exactly_good,"[communication, convenient, exactly, good, exc...","[Beautiful spot! Comfortable, clean and cute.,..."
5,4,722,4_montana_yellowstone_ski_state,"[montana, yellowstone, ski, state, skiing, sky...",[What a wonderful Airbnb!!<br/>Super cute and ...
6,5,511,5_basement_bedroom_noise_shower,"[basement, bedroom, noise, shower, bathroom, u...",[Exceptionally clean with great amenities! Com...
7,6,389,6_heart_weekend_base_visiting,"[heart, weekend, base, visiting, spot, getaway...",[I would absolutely stay in this little gem ag...
8,7,331,7_enjoyed_good_vey_thanks,"[enjoyed, good, vey, thanks, thank, wonderful,...","[Nice place, good location, had a really good ..."
9,8,312,8_brilliant_spot_good_awesome,"[brilliant, spot, good, awesome, advertised, t...","[great spot, as advertised!, Great spot. As a..."
10,9,283,9_uncomfortable_did_sleep_loud,"[uncomfortable, did, sleep, loud, night, dirty...",[worst host experience ever. 0 stars . worst ...
11,10,268,10_second_definitely_repeat_book,"[second, definitely, repeat, book, come, forwa...",[A repeat stay for us and the place was just a...
12,11,235,11_beds_bed_comfy_shower,"[beds, bed, comfy, shower, sleep, bathroom, pi...","[This spot is cute and cozy - great linens, co..."
13,12,197,12_hosts_host_accommodating_awesome,"[hosts, host, accommodating, awesome, staff, a...",[Everything was great and exactly as described...
14,13,153,13_house_beautiful_home_comforts,"[house, beautiful, home, comforts, yard, apart...",[Beautiful home. Very comfortable and a wonder...
15,14,123,14_dog_dogs_joe_yard,"[dog, dogs, joe, yard, fenced, huck, hilary, p...","[Great spot, the fenced backyard was great for..."
16,15,121,15_kitchen_meals_cooking_cook,"[kitchen, meals, cooking, cook, stocked, equip...",[The house is awesome! Great location - conven...
17,16,110,16_near_close_right_main,"[near, close, right, main, stadium, downtown, ...",[Great place right near the heart of downtown!...
18,17,108,17_一切都很完美_设施非常全_虽然是地下室_生活配套设施齐全,"[一切都很完美, 设施非常全, 虽然是地下室, 生活配套设施齐全, 洗衣机好像不太好用, 有...","[房间是地下室，价格比较实惠，如果临时住一天还不错🤓，房间很干净，洗衣机好像不太好用, 房间..."
19,18,88,18_quiet_comunucation_whit_accuracy,"[quiet, comunucation, whit, accuracy, reflecti...","[Clean, quiet, comfortable and a great locatio..."
20,19,81,19_second_2nd_time_year,"[second, 2nd, time, year, love, staying, tear,...",[This was the second time we have stayed at Br...
21,20,75,20_hostel_soon_rent_come,"[hostel, soon, rent, come, exists, slay, ll, b...","[Amazingly amazing hostel & great people!, Lov..."
22,21,54,21_ve_airbnb_best_favorite,"[ve, airbnb, best, favorite, stayed, airbnbs, ...",[Hands down the best Airbnb space I’ve been to...
23,22,51,22_muy_la_el_es,"[muy, la, el, es, sehr, und, war, wir, en, que]",[Fue una estancia muy corta pero sin duda volv...
24,23,50,23_na_gg_aa_hostile,"[na, gg, aa, hostile, אהבנו, xxx, ggg, ndnedjj...","[Use my previous comments, Na, na]"
25,24,38,24_couldn_asked_bro_staycationing,"[couldn, asked, bro, staycationing, masks, cus...",[We couldn’t have asked for better people to r...
26,25,26,25_longer_wish_stayed_trendiest,"[longer, wish, stayed, trendiest, sto, everthi...",[We really enjoyed staying here and wish we co...
27,26,25,26_ski_skiing_bridger_bowl,"[ski, skiing, bridger, bowl, convene, vacay, c...",[Great! Very responsive host. Place was close ...

**Top Ten Words**

This is the top 10 words of your BERTopics model topics. Take a screenshot of the words and see if you can assign names for the different topics as you understand them based on the words in your printout. If you would like to see more words from each topic then change the 'num_top_words' variable.

In [24]:
topic_model.topic_representations_

{-1: [('enjoyed', np.float64(0.14760236950784372)),
  ('loved', np.float64(0.14490672976557276)),
  ('stayed', np.float64(0.14381540889235864)),
  ('cozy', np.float64(0.14339383920872056)),
  ('needed', np.float64(0.14294641961289473)),
  ('town', np.float64(0.1424667932366994)),
  ('time', np.float64(0.14240818595355406)),
  ('family', np.float64(0.14230197552595783)),
  ('staying', np.float64(0.14227668889465744)),
  ('just', np.float64(0.14220758345853224))],
 0: [('coffee', np.float64(0.1609423818056054)),
  ('kitchen', np.float64(0.15151133393420158)),
  ('airbnb', np.float64(0.14925227859697754)),
  ('loved', np.float64(0.1478862152572772)),
  ('walk', np.float64(0.14730474352825407)),
  ('family', np.float64(0.1470294624465637)),
  ('stocked', np.float64(0.146939668542717)),
  ('neighborhood', np.float64(0.14540500193184233)),
  ('needed', np.float64(0.14520336926964045)),
  ('staying', np.float64(0.1447261319556301))],
 1: [('helpful', np.float64(0.2478151184760761)),
  ('responsive', np.float64(0.23224782616807754)),
  ('host', np.float64(0.23026136071023376)),
  ('communication', np.float64(0.22792822580980834)),
  ('accommodating', np.float64(0.2270745920548688)),
  ('hosts', np.float64(0.1991558077891722)),
  ('respond', np.float64(0.19679366821853542)),
  ('described', np.float64(0.19529461519803723)),
  ('friendly', np.float64(0.1946210863437959)),
  ('super', np.float64(0.19300382719188922))],
 2: [('distance', np.float64(0.278565099732847)),
  ('walkable', np.float64(0.2626328605030638)),
  ('walking', np.float64(0.2597758870579944)),
  ('quiet', np.float64(0.2547913632951736)),
  ('restaurants', np.float64(0.24875820394687284)),
  ('neighborhood', np.float64(0.24515439664875457)),
  ('downtown', np.float64(0.23582786482652965)),
  ('walk', np.float64(0.23355701990066483)),
  ('close', np.float64(0.2315091820255323)),
  ('street', np.float64(0.22580326785257968))],
 3: [('communication', np.float64(0.2787061829903962)),
  ('convenient', np.float64(0.26837510961219785)),
  ('exactly', np.float64(0.25700264177364884)),
  ('good', np.float64(0.25620835927231356)),
  ('excellent', np.float64(0.25101833876499047)),
  ('advertised', np.float64(0.24977387924715636)),
  ('value', np.float64(0.2487214157594743)),
  ('cute', np.float64(0.24812305253855943)),
  ('thank', np.float64(0.24478489279896393)),
  ('spot', np.float64(0.24343656298454236))],
 4: [('montana', np.float64(0.3622460787788703)),
  ('yellowstone', np.float64(0.34196408605094114)),
  ('ski', np.float64(0.2673173079207762)),
  ('state', np.float64(0.25564619831248403)),
  ('skiing', np.float64(0.24278060505572038)),
  ('sky', np.float64(0.2300309485747163)),
  ('mountains', np.float64(0.22994646321603845)),
  ('mountain', np.float64(0.22814735459115482)),
  ('bridger', np.float64(0.22670991527523124)),
  ('snow', np.float64(0.2227232912928513))],
 5: [('basement', np.float64(0.25253422770055034)),
  ('bedroom', np.float64(0.23224061716471892)),
  ('noise', np.float64(0.22384867773404565)),
  ('shower', np.float64(0.21092974162551087)),
  ('bathroom', np.float64(0.2079557429076162)),
  ('use', np.float64(0.20420641100844347)),
  ('sleep', np.float64(0.20099370690579071)),
  ('apartment', np.float64(0.19891822472365797)),
  ('didn', np.float64(0.19390321058946391)),
  ('bed', np.float64(0.19390202685303135))],
 6: [('heart', np.float64(0.30885855606981816)),
  ('weekend', np.float64(0.2825967876542816)),
  ('base', np.float64(0.2714633854015147)),
  ('visiting', np.float64(0.26800108254976607)),
  ('spot', np.float64(0.25230280230054797)),
  ('getaway', np.float64(0.24253223516335642)),
  ('fantastic', np.float64(0.2346320071739788)),
  ('bozeman', np.float64(0.21646105133186647)),
  ('time', np.float64(0.21339212591255638)),
  ('overnight', np.float64(0.2132481131041295))],
 7: [('enjoyed', np.float64(0.3262406617291466)),
  ('good', np.float64(0.29180256077056227)),
  ('vey', np.float64(0.27869407221218745)),
  ('thanks', np.float64(0.26808391781932794)),
  ('thank', np.float64(0.26725079837531024)),
  ('wonderful', np.float64(0.2594181492250941)),
  ('staying', np.float64(0.24679169960161376)),
  ('highly', np.float64(0.2467688858559077)),
  ('darling', np.float64(0.23456226906886302)),
  ('nice', np.float64(0.23319186389670007))],
 8: [('brilliant', np.float64(0.4581989183649567)),
  ('spot', np.float64(0.4263948650354809)),
  ('good', np.float64(0.415476111871803)),
  ('awesome', np.float64(0.4032587397856226)),
  ('advertised', np.float64(0.38113043338377345)),
  ('thank', np.float64(0.380518670947903)),
  ('rly', np.float64(0.3789493772451003)),
  ('stat', np.float64(0.3789493772451003)),
  ('okace', np.float64(0.3789493772451003)),
  ('price', np.float64(0.3683592960262044))],
 9: [('uncomfortable', np.float64(0.25768630344091303)),
  ('did', np.float64(0.25053311665552874)),
  ('sleep', np.float64(0.24676868589555256)),
  ('loud', np.float64(0.24486745089716697)),
  ('night', np.float64(0.2413491427752187)),
  ('dirty', np.float64(0.2374937190939562)),
  ('wasn', np.float64(0.23708154914582316)),
  ('basement', np.float64(0.22853076595971109)),
  ('bad', np.float64(0.22330240682667649)),
  ('didn', np.float64(0.22261756691375428))],
 10: [('second', np.float64(0.40519698095786155)),
  ('definitely', np.float64(0.34566332413719425)),
  ('repeat', np.float64(0.3210319098140265)),
  ('book', np.float64(0.3135492308128082)),
  ('come', np.float64(0.30151836059054665)),
  ('forward', np.float64(0.30063701448968677)),
  ('time', np.float64(0.29890190640086733)),
  ('visits', np.float64(0.2947442270405288)),
  ('staying', np.float64(0.29218812193873733)),
  ('arises', np.float64(0.29004999331046766))],
 11: [('beds', np.float64(0.45492476479276284)),
  ('bed', np.float64(0.4500870450023238)),
  ('comfy', np.float64(0.4159438667173075)),
  ('shower', np.float64(0.2927491008802011)),
  ('sleep', np.float64(0.2853725777663537)),
  ('bathroom', np.float64(0.25927176041148536)),
  ('pillows', np.float64(0.25100751807003147)),
  ('sheets', np.float64(0.2476555001347939)),
  ('mattress', np.float64(0.23776154832396268)),
  ('comfortable', np.float64(0.23469318962836616))],
 12: [('hosts', np.float64(0.5117347059542656)),
  ('host', np.float64(0.511127284389607)),
  ('accommodating', np.float64(0.3782292048570782)),
  ('awesome', np.float64(0.3299092175074594)),
  ('staff', np.float64(0.3194318937225111)),
  ('accommodations', np.float64(0.306981777413884)),
  ('attentive', np.float64(0.29249876393053864)),
  ('hosting', np.float64(0.28868517496173335)),
  ('witty', np.float64(0.2772916885067432)),
  ('gréât', np.float64(0.2772916885067432))],
 13: [('house', np.float64(0.4125662646798846)),
  ('beautiful', np.float64(0.38544391716968496)),
  ('home', np.float64(0.3695818365142543)),
  ('comforts', np.float64(0.36826225694640236)),
  ('yard', np.float64(0.3639950144870229)),
  ('apartment', np.float64(0.35144786481234513)),
  ('awesome', np.float64(0.3497802514695318)),
  ('townhouse', np.float64(0.34975878872307886)),
  ('wonderful', np.float64(0.33247665404607957)),
  ('serviced', np.float64(0.3286946949679959))],
 14: [('dog', np.float64(0.7038203433030804)),
  ('dogs', np.float64(0.6710531978187426)),
  ('joe', np.float64(0.5535156572606129)),
  ('yard', np.float64(0.39343985955019584)),
  ('fenced', np.float64(0.38918575390709614)),
  ('huck', np.float64(0.3509870647282032)),
  ('hilary', np.float64(0.3078698363201215)),
  ('pup', np.float64(0.2909985801820014)),
  ('sweet', np.float64(0.2840304715798566)),
  ('friendly', np.float64(0.2817046973690155))],
 15: [('kitchen', np.float64(0.4630895935061313)),
  ('meals', np.float64(0.423054577343285)),
  ('cooking', np.float64(0.39232215590285985)),
  ('cook', np.float64(0.3788716204348086)),
  ('stocked', np.float64(0.3324146533748397)),
  ('equipped', np.float64(0.3077830437048313)),
  ('fully', np.float64(0.300674987267605)),
  ('meal', np.float64(0.29705271683500845)),
  ('equipment', np.float64(0.28236249880043723)),
  ('hill', np.float64(0.27032601719760857))],
 16: [('near', np.float64(0.47603398029981575)),
  ('close', np.float64(0.45929359123747165)),
  ('right', np.float64(0.4274409572796208)),
  ('main', np.float64(0.4112741448203949)),
  ('stadium', np.float64(0.4100273368084797)),
  ('downtown', np.float64(0.3958641949987242)),
  ('uptown', np.float64(0.38413833689251364)),
  ('street', np.float64(0.38170280493474523)),
  ('artist', np.float64(0.3622368689599119)),
  ('heart', np.float64(0.34639178993120023))],
 17: [('一切都很完美', np.float64(0.5771365517873859)),
  ('设施非常全', np.float64(0.5771365517873859)),
  ('虽然是地下室', np.float64(0.5771365517873859)),
  ('生活配套设施齐全', np.float64(0.5771365517873859)),
  ('洗衣机好像不太好用', np.float64(0.5771365517873859)),
  ('有机会还会推荐朋友入住', np.float64(0.5771365517873859)),
  ('有很多便利店和餐馆', np.float64(0.5771365517873859)),
  ('是一次愉快的体验', np.float64(0.5771365517873859)),
  ('推荐大家来', np.float64(0.5771365517873859)),
  ('房间虽然是地下室', np.float64(0.5771365517873859))],
 18: [('quiet', np.float64(0.7499777151809415)),
  ('comunucation', np.float64(0.41283513171981523)),
  ('whit', np.float64(0.41283513171981523)),
  ('accuracy', np.float64(0.38929752942800616)),
  ('reflection', np.float64(0.37379370714626875)),
  ('beaten', np.float64(0.35296733198120506)),
  ('respected', np.float64(0.34526988607581904)),
  ('simple', np.float64(0.3436249516588036)),
  ('frills', np.float64(0.33290893405636174)),
  ('hideaway', np.float64(0.3189805667005656))],
 19: [('second', np.float64(0.903027474091916)),
  ('2nd', np.float64(0.40515404475041905)),
  ('time', np.float64(0.3969373304850252)),
  ('year', np.float64(0.3831017300130296)),
  ('love', np.float64(0.3476642229414593)),
  ('staying', np.float64(0.32365108544657034)),
  ('tear', np.float64(0.31917302542216924)),
  ('likely', np.float64(0.3012415599882394)),
  ('apart', np.float64(0.27988643405903896)),
  ('wear', np.float64(0.27988643405903896))],
 20: [('hostel', np.float64(0.8455329597984667)),
  ('soon', np.float64(0.6083407958497423)),
  ('rent', np.float64(0.5359871050460128)),
  ('come', np.float64(0.5024083429322338)),
  ('exists', np.float64(0.49852373537208955)),
  ('slay', np.float64(0.49852373537208955)),
  ('ll', np.float64(0.4716667689665716)),
  ('book', np.float64(0.4426857388666548)),
  ('return', np.float64(0.4379570054590953)),
  ('tho', np.float64(0.4262296962725881))],
 21: [('ve', np.float64(0.6059629178722693)),
  ('airbnb', np.float64(0.5879069033528674)),
  ('best', np.float64(0.5596884256422144)),
  ('favorite', np.float64(0.45815917747939483)),
  ('stayed', np.float64(0.45399833358955427)),
  ('airbnbs', np.float64(0.4527587404972688)),
  ('bnbs', np.float64(0.36492642813488163)),
  ('aesthetic', np.float64(0.36148218549007893)),
  ('johanna', np.float64(0.34901524256268285)),
  ('airbnbdom', np.float64(0.34901524256268285))],
 22: [('muy', np.float64(0.86743902880073)),
  ('la', np.float64(0.76115393144437)),
  ('el', np.float64(0.7432610480017945)),
  ('es', np.float64(0.7432610480017945)),
  ('sehr', np.float64(0.7089479709353067)),
  ('und', np.float64(0.6831593587052913)),
  ('war', np.float64(0.6831593587052913)),
  ('wir', np.float64(0.6709178944227203)),
  ('en', np.float64(0.6639586640704519)),
  ('que', np.float64(0.6501862706471044))],
 23: [('na', np.float64(2.392178149202701)),
  ('gg', np.float64(1.8681992079979657)),
  ('aa', np.float64(1.8681992079979657)),
  ('hostile', np.float64(1.8681992079979657)),
  ('אהבנו', np.float64(1.8681992079979657)),
  ('xxx', np.float64(1.8681992079979657)),
  ('ggg', np.float64(1.8681992079979657)),
  ('ndnedjjek', np.float64(1.8681992079979657)),
  ('po', np.float64(1.7616847023730604)),
  ('yeehaw', np.float64(1.7616847023730604))],
 24: [('couldn', np.float64(0.5380695547449938)),
  ('asked', np.float64(0.4426030879336201)),
  ('bro', np.float64(0.43666265769049173)),
  ('staycationing', np.float64(0.43666265769049173)),
  ('masks', np.float64(0.41176654012998654)),
  ('customers', np.float64(0.41176654012998654)),
  ('better', np.float64(0.3993556907859921)),
  ('bothersome', np.float64(0.39536788671669326)),
  ('think', np.float64(0.39414281299456055)),
  ('refuge', np.float64(0.3831195709313465))],
 25: [('longer', np.float64(1.112520823163096)),
  ('wish', np.float64(0.9885006916264225)),
  ('stayed', np.float64(0.5617543191299781)),
  ('trendiest', np.float64(0.5535239999678162)),
  ('sto', np.float64(0.5535239999678162)),
  ('everthing', np.float64(0.5219650875372334)),
  ('wished', np.float64(0.5167999874100395)),
  ('micheal', np.float64(0.4856515061065414)),
  ('dont', np.float64(0.4856515061065414)),
  ('frequent', np.float64(0.46293339332086314))],
 26: [('ski', np.float64(0.9773330563532153)),
  ('skiing', np.float64(0.8574565962436227)),
  ('bridger', np.float64(0.6492942663695326)),
  ('bowl', np.float64(0.6194783019365074)),
  ('convene', np.float64(0.5514233320482426)),
  ('vacay', np.float64(0.5199841882183408)),
  ('charms', np.float64(0.4992757535789128)),
  ('skiers', np.float64(0.48380841973805516)),
  ('trip', np.float64(0.4817087625873989)),
  ('hills', np.float64(0.45236927590815346))]}

#Screen Shot #3 -

Another way to look at the top ten words in a dataframe and not a python dictionary. Take a screenshot of your topics and move the scroll at the bottom if needed to get all topics in the screenshot.

In [25]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import lit
import pandas as pd


topic_representations = topic_model.topic_representations_

max_terms = max(len(words) for words in topic_representations.values())

data_dict = {}
for topic_id, word_scores in topic_representations.items():
     words = [f"{word} ({score:.4f})" for word, score in word_scores]
     while len(words) < max_terms:
      words.append(None)
     data_dict[f"Topic_{topic_id}"] = words

pandas_df = pd.DataFrame(data_dict)
spark_df = spark.createDataFrame(pandas_df)

# Show result
spark_df.show(truncate=False)

+----------------+---------------------+----------------------+---------------------+----------------------+--------------------+------------------+------------------+------------------+-------------------+----------------------+-------------------+--------------------+-----------------------+------------------+-----------------+------------------+-----------------+-------------------------------+---------------------+----------------+---------------+------------------+-------------+------------------+----------------------+------------------+----------------+
|Topic_-1        |Topic_0              |Topic_1               |Topic_2              |Topic_3               |Topic_4             |Topic_5           |Topic_6           |Topic_7           |Topic_8            |Topic_9               |Topic_10           |Topic_11            |Topic_12               |Topic_13          |Topic_14         |Topic_15          |Topic_16         |Topic_17                       |Topic_18             |Topic_19        |Topic_20       |Topic_21          |Topic_22     |Topic_23          |Topic_24              |Topic_25          |Topic_26        |
+----------------+---------------------+----------------------+---------------------+----------------------+--------------------+------------------+------------------+------------------+-------------------+----------------------+-------------------+--------------------+-----------------------+------------------+-----------------+------------------+-----------------+-------------------------------+---------------------+----------------+---------------+------------------+-------------+------------------+----------------------+------------------+----------------+
|enjoyed (0.1476)|coffee (0.1609)      |helpful (0.2478)      |distance (0.2786)    |communication (0.2787)|montana (0.3622)    |basement (0.2525) |heart (0.3089)    |enjoyed (0.3262)  |brilliant (0.4582) |uncomfortable (0.2577)|second (0.4052)    |beds (0.4549)       |hosts (0.5117)         |house (0.4126)    |dog (0.7038)     |kitchen (0.4631)  |near (0.4760)    |一切都很完美 (0.5771)          |quiet (0.7500)       |second (0.9030) |hostel (0.8455)|ve (0.6060)       |muy (0.8674) |na (2.3922)       |couldn (0.5381)       |longer (1.1125)   |ski (0.9773)    |
|loved (0.1449)  |kitchen (0.1515)     |responsive (0.2322)   |walkable (0.2626)    |convenient (0.2684)   |yellowstone (0.3420)|bedroom (0.2322)  |weekend (0.2826)  |good (0.2918)     |spot (0.4264)      |did (0.2505)          |definitely (0.3457)|bed (0.4501)        |host (0.5111)          |beautiful (0.3854)|dogs (0.6711)    |meals (0.4231)    |close (0.4593)   |设施非常全 (0.5771)            |comunucation (0.4128)|2nd (0.4052)    |soon (0.6083)  |airbnb (0.5879)   |la (0.7612)  |gg (1.8682)       |asked (0.4426)        |wish (0.9885)     |skiing (0.8575) |
|stayed (0.1438) |airbnb (0.1493)      |host (0.2303)         |walking (0.2598)     |exactly (0.2570)      |ski (0.2673)        |noise (0.2238)    |base (0.2715)     |vey (0.2787)      |good (0.4155)      |sleep (0.2468)        |repeat (0.3210)    |comfy (0.4159)      |accommodating (0.3782) |home (0.3696)     |joe (0.5535)     |cooking (0.3923)  |right (0.4274)   |虽然是地下室 (0.5771)          |whit (0.4128)        |time (0.3969)   |rent (0.5360)  |best (0.5597)     |el (0.7433)  |aa (1.8682)       |bro (0.4367)          |stayed (0.5618)   |bridger (0.6493)|
|cozy (0.1434)   |loved (0.1479)       |communication (0.2279)|quiet (0.2548)       |good (0.2562)         |state (0.2556)      |shower (0.2109)   |visiting (0.2680) |thanks (0.2681)   |awesome (0.4033)   |loud (0.2449)         |book (0.3135)      |shower (0.2927)     |awesome (0.3299)       |comforts (0.3683) |yard (0.3934)    |cook (0.3789)     |main (0.4113)    |生活配套设施齐全 (0.5771)      |accuracy (0.3893)    |year (0.3831)   |come (0.5024)  |favorite (0.4582) |es (0.7433)  |hostile (1.8682)  |staycationing (0.4367)|trendiest (0.5535)|bowl (0.6195)   |
|needed (0.1429) |walk (0.1473)        |accommodating (0.2271)|restaurants (0.2488) |excellent (0.2510)    |skiing (0.2428)     |bathroom (0.2080) |spot (0.2523)     |thank (0.2673)    |advertised (0.3811)|night (0.2413)        |come (0.3015)      |sleep (0.2854)      |staff (0.3194)         |yard (0.3640)     |fenced (0.3892)  |stocked (0.3324)  |stadium (0.4100) |洗衣机好像不太好用 (0.5771)    |reflection (0.3738)  |love (0.3477)   |exists (0.4985)|stayed (0.4540)   |sehr (0.7089)|אהבנו (1.8682)    |masks (0.4118)        |sto (0.5535)      |convene (0.5514)|
|town (0.1425)   |family (0.1470)      |hosts (0.1992)        |neighborhood (0.2452)|advertised (0.2498)   |sky (0.2300)        |use (0.2042)      |getaway (0.2425)  |wonderful (0.2594)|thank (0.3805)     |dirty (0.2375)        |forward (0.3006)   |bathroom (0.2593)   |accommodations (0.3070)|apartment (0.3514)|huck (0.3510)    |equipped (0.3078) |downtown (0.3959)|有机会还会推荐朋友入住 (0.5771)|beaten (0.3530)      |staying (0.3237)|slay (0.4985)  |airbnbs (0.4528)  |und (0.6832) |xxx (1.8682)      |customers (0.4118)    |everthing (0.5220)|vacay (0.5200)  |
|time (0.1424)   |stocked (0.1469)     |respond (0.1968)      |downtown (0.2358)    |value (0.2487)        |mountains (0.2299)  |sleep (0.2010)    |fantastic (0.2346)|staying (0.2468)  |rly (0.3789)       |wasn (0.2371)         |time (0.2989)      |pillows (0.2510)    |attentive (0.2925)     |awesome (0.3498)  |hilary (0.3079)  |fully (0.3007)    |uptown (0.3841)  |有很多便利店和餐馆 (0.5771)    |respected (0.3453)   |tear (0.3192)   |ll (0.4717)    |bnbs (0.3649)     |war (0.6832) |ggg (1.8682)      |better (0.3994)       |wished (0.5168)   |charms (0.4993) |
|family (0.1423) |neighborhood (0.1454)|described (0.1953)    |walk (0.2336)        |cute (0.2481)         |mountain (0.2281)   |apartment (0.1989)|bozeman (0.2165)  |highly (0.2468)   |stat (0.3789)      |basement (0.2285)     |visits (0.2947)    |sheets (0.2477)     |hosting (0.2887)       |townhouse (0.3498)|pup (0.2910)     |meal (0.2971)     |street (0.3817)  |是一次愉快的体验 (0.5771)      |simple (0.3436)      |likely (0.3012) |book (0.4427)  |aesthetic (0.3615)|wir (0.6709) |ndnedjjek (1.8682)|bothersome (0.3954)   |micheal (0.4857)  |skiers (0.4838) |
|staying (0.1423)|needed (0.1452)      |friendly (0.1946)     |close (0.2315)       |thank (0.2448)        |bridger (0.2267)    |didn (0.1939)     |time (0.2134)     |darling (0.2346)  |okace (0.3789)     |bad (0.2233)          |staying (0.2922)   |mattress (0.2378)   |witty (0.2773)         |wonderful (0.3325)|sweet (0.2840)   |equipment (0.2824)|artist (0.3622)  |推荐大家来 (0.5771)            |frills (0.3329)      |apart (0.2799)  |return (0.4380)|johanna (0.3490)  |en (0.6640)  |po (1.7617)       |think (0.3941)        |dont (0.4857)     |trip (0.4817)   |
|just (0.1422)   |staying (0.1447)     |super (0.1930)        |street (0.2258)      |spot (0.2434)         |snow (0.2227)       |bed (0.1939)      |overnight (0.2132)|nice (0.2332)     |price (0.3684)     |didn (0.2226)         |arises (0.2900)    |comfortable (0.2347)|gréât (0.2773)         |serviced (0.3287) |friendly (0.2817)|hill (0.2703)     |heart (0.3464)   |房间虽然是地下室 (0.5771)      |hideaway (0.3190)    |wear (0.2799)   |tho (0.4262)   |airbnbdom (0.3490)|que (0.6502) |yeehaw (1.7617)   |refuge (0.3831)       |frequent (0.4629) |hills (0.4524)  |
+----------------+---------------------+----------------------+---------------------+----------------------+--------------------+------------------+------------------+------------------+-------------------+----------------------+-------------------+--------------------+-----------------------+------------------+-----------------+------------------+-----------------+-------------------------------+---------------------+----------------+---------------+------------------+-------------+------------------+----------------------+------------------+----------------+

**Topic Labels**

The generate_topic_labels command will automatically put the top words as a label. This does not really describe the topics in a human sense. That is your job.

In [26]:
topic_model.generate_topic_labels(nr_words=4)

['-1_enjoyed_loved_stayed_cozy',
 '0_coffee_kitchen_airbnb_loved',
 '1_helpful_responsive_host_communication',
 '2_distance_walkable_walking_quiet',
 '3_communication_convenient_exactly_good',
 '4_montana_yellowstone_ski_state',
 '5_basement_bedroom_noise_shower',
 '6_heart_weekend_base_visiting',
 '7_enjoyed_good_vey_thanks',
 '8_brilliant_spot_good_awesome',
 '9_uncomfortable_did_sleep_loud',
 '10_second_definitely_repeat_book',
 '11_beds_bed_comfy_shower',
 '12_hosts_host_accommodating_awesome',
 '13_house_beautiful_home_comforts',
 '14_dog_dogs_joe_yard',
 '15_kitchen_meals_cooking_cook',
 '16_near_close_right_main',
 '17_一切都很完美_设施非常全_虽然是地下室_生活配套设施齐全',
 '18_quiet_comunucation_whit_accuracy',
 '19_second_2nd_time_year',
 '20_hostel_soon_rent_come',
 '21_ve_airbnb_best_favorite',
 '22_muy_la_el_es',
 '23_na_gg_aa_hostile',
 '24_couldn_asked_bro_staycationing',
 '25_longer_wish_stayed_trendiest',
 '26_ski_skiing_bridger_bowl']

**Other investigations of the Topics**

Another variation of looking at the top 10 words in the topics and the weight assigned to that word to represent the topic.

This is a way to look at the top ten words of a given topic.

In [27]:
topic_model.get_topic(3)

[('communication', np.float64(0.2787061829903962)),
 ('convenient', np.float64(0.26837510961219785)),
 ('exactly', np.float64(0.25700264177364884)),
 ('good', np.float64(0.25620835927231356)),
 ('excellent', np.float64(0.25101833876499047)),
 ('advertised', np.float64(0.24977387924715636)),
 ('value', np.float64(0.2487214157594743)),
 ('cute', np.float64(0.24812305253855943)),
 ('thank', np.float64(0.24478489279896393)),
 ('spot', np.float64(0.24343656298454236))]

`topic_model.get_topic_freq()`

Command lets us see the frequency of each topic identified by the model.

In [28]:
topic_model.get_topic_freq()

    Topic  Count
1       0   5768
0      -1   5249
2       1   1299
7       2   1218
11      3    891
3       4    722
8       5    511
9       6    389
13      7    331
20      8    312
21      9    283
12     10    268
17     11    235
4      12    197
16     13    153
6      14    123
18     15    121
14     16    110
25     17    108
10     18     88
5      19     81
23     20     75
15     21     54
26     22     51
19     23     50
24     24     38
27     25     26
22     26     25

In [29]:
topic_model.visualize_topics()

In [30]:
topic_model.visualize_documents(comments, embeddings=embeddings, hide_annotations=True, hide_document_hover=False, custom_labels=True)

NameError: name 'comments' is not defined

# Going Further

Now we can add another application to our understanding of the dataset and see if the topics being discussed can be used to predict whether or not the host is a superhost. We will use the RandomForestClassifier from the included pyspark ml library.

This next code loads up the expanded **listings.csv** from insideairbnb that was used for HW #2 (It is okay to have a different city if you have to change to an English speaking city) but make sure that you use the condensed listings file from the new city.

In [35]:
listingsDF =spark.read.options(mode='FAILFAST',
                              header = True,
                              multiLine=True,
                              inferSchema=True,
                              escape='"').csv("/content/listings (2).csv") #You will need to replace this with your file path

In [38]:
listingsDF = listingsDF.select("id","host_name","host_id","number_of_reviews", "price")

In [39]:
import pandas as pd
df = pd.DataFrame({"comments": reviews['comments'], "Topic": topic_model.topics_, "listing_id": reviews['listing_id'] })
documentTopics_df = spark.createDataFrame(df)

In [40]:
from pyspark.sql import functions as F

pivot_df = documentTopics_df.groupBy("listing_id").pivot("Topic").agg(F.count("Topic"))

result_df = pivot_df.groupBy("listing_id").agg(*[F.sum(c).alias(c) for c in pivot_df.columns if c != "listing_id"]).fillna(0)


result_df.show()

+-------------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
|         listing_id| -1|  0|  1|  2|  3|  4|  5|  6|  7|  8|  9| 10| 11| 12| 13| 14| 15| 16| 17| 18| 19| 20| 21| 22| 23| 24| 25| 26|
+-------------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
|           50675728|  8| 22|  4|  3|  2|  1|  0|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|
| 744478255073405873| 12| 29|  7|  1|  2|  7|  2|  0|  2|  1|  0|  0|  1|  2|  2|  0|  1|  0|  1|  0|  0|  1|  1|  0|  0|  0|  0|  0|
|            9740033| 11|  5|  0|  0|  4|  0|  2|  0|  0|  3|  1|  0|  0|  3|  0|  0|  0|  0|  0|  0|  1|  2|  0|  1|  1|  0|  0|  0|
|           45075319| 47| 59| 17|  8| 12|  7|  2|  5|  2|  4|  2|  7|  4|  3|  1|  0|  0|  0|  0|  1|  0|  1|  1|  0|  0|  0|  1|  0|
|1108037590849320235|  2|  2|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|
|1040565103561819864| 10| 14|  5|  8|  2|  0|  3|  0|  3|  0|  0|  0|  0|  1|  0|  0|  0|  1|  0|  0|  0|  0|  2|  0|  1|  0|  0|  0|
|1314082323149340257|  3|  0|  2|  1|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|
|           25580821|  8|  9|  2|  3|  5|  4|  0|  0|  0|  1|  1|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  1|
|           46570803|  1|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|
| 684167798771337575| 13| 14|  4|  5|  2|  1|  2|  0|  0|  0|  0|  1|  1|  0|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|
|           22031083|  2|  3|  0|  1|  0|  2|  0|  0|  1|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  1|  0|  0|
| 705082802450406622|  8|  5|  1|  3|  4|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|
|           53281258|  2|  5|  0|  1|  0|  3|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|
|1113152204237576730|  1|  2|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|
|           14769819| 20| 26|  2|  0|  4|  4|  5|  0|  1|  1|  3|  1|  1|  3|  0|  0|  0|  0|  0|  0|  1|  0|  1|  0|  0|  0|  0|  0|
|           51825573| 23| 15|  4|  3|  4|  1|  1|  1|  0|  0|  1|  0|  0|  0|  2|  0|  0|  1|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|
| 607365320794077990|  1|  4|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|
|           39002591| 38| 51|  8|  6|  6|  9|  1|  5|  5|  1|  2|  0|  3|  0|  0|  0|  2|  1|  0|  0|  0|  1|  0|  0|  1|  0|  0|  0|
|            1950545|  6|  4|  1|  1|  1|  0|  0|  1|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|
| 577635693880635570| 13| 14|  3|  4|  4|  2|  1|  0|  0|  1|  1|  0|  1|  1|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|
+-------------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
only showing top 20 rows

In [41]:
totalsDF = result_df.join(listingsDF,result_df.listing_id == listingsDF.id).drop(listingsDF.id)
totalsDF.show(truncate=True)

+-------------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+--------------------+---------+-----------------+-----+
|         listing_id| -1|  0|  1|  2|  3|  4|  5|  6|  7|  8|  9| 10| 11| 12| 13| 14| 15| 16| 17| 18| 19| 20| 21| 22| 23| 24| 25| 26|           host_name|  host_id|number_of_reviews|price|
+-------------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+--------------------+---------+-----------------+-----+
|           50675728|  8| 22|  4|  3|  2|  1|  0|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|              Carrie| 87338185|              107|  166|
| 744478255073405873| 12| 29|  7|  1|  2|  7|  2|  0|  2|  1|  0|  0|  1|  2|  2|  0|  1|  0|  1|  0|  0|  1|  1|  0|  0|  0|  0|  0|             Brandon| 87807117|              174|  318|
|            9740033| 11|  5|  0|  0|  4|  0|  2|  0|  0|  3|  1|  0|  0|  3|  0|  0|  0|  0|  0|  0|  1|  2|  0|  1|  1|  0|  0|  0|                Nina| 49746531|               98|   44|
|           45075319| 47| 59| 17|  8| 12|  7|  2|  5|  2|  4|  2|  7|  4|  3|  1|  0|  0|  0|  0|  1|  0|  1|  1|  0|  0|  0|  1|  0|                Luke|219957508|              509|  113|
|1108037590849320235|  2|  2|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|           Catherine| 39660084|               19|  117|
|1040565103561819864| 10| 14|  5|  8|  2|  0|  3|  0|  3|  0|  0|  0|  0|  1|  0|  0|  0|  1|  0|  0|  0|  0|  2|  0|  1|  0|  0|  0|              Payton|545489115|              106|  155|
|1314082323149340257|  3|  0|  2|  1|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|             Maureen|131212957|               19|  115|
|           25580821|  8|  9|  2|  3|  5|  4|  0|  0|  0|  1|  1|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  1|Vacation Homes Bo...|106429221|               97|  215|
|           46570803|  1|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|                Evan|  8675457|                3|   92|
| 684167798771337575| 13| 14|  4|  5|  2|  1|  2|  0|  0|  0|  0|  1|  1|  0|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|                Neil|388858579|              122|  116|
|           22031083|  2|  3|  0|  1|  0|  2|  0|  0|  1|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  1|  0|  0|       Mountain Home|158595657|               28|  344|
| 705082802450406622|  8|  5|  1|  3|  4|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|                 Liz| 87300632|               51|  271|
|           53281258|  2|  5|  0|  1|  0|  3|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|    Joe And Michelle|225774632|               35|  263|
|1113152204237576730|  1|  2|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|           Christina|138031362|                3|  110|
|           14769819| 20| 26|  2|  0|  4|  4|  5|  0|  1|  1|  3|  1|  1|  3|  0|  0|  0|  0|  0|  0|  1|  0|  1|  0|  0|  0|  0|  0|       Ellen-Therese| 84377290|              185|   68|
|           51825573| 23| 15|  4|  3|  4|  1|  1|  1|  0|  0|  1|  0|  0|  0|  2|  0|  0|  1|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|          Alexandria|  1259005|              135|  157|
| 607365320794077990|  1|  4|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|              Louisa| 69417001|               14|   45|
|           39002591| 38| 51|  8|  6|  6|  9|  1|  5|  5|  1|  2|  0|  3|  0|  0|  0|  2|  1|  0|  0|  0|  1|  0|  0|  1|  0|  0|  0|             Phillip| 45830254|              336|   89|
|            1950545|  6|  4|  1|  1|  1|  0|  0|  1|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|                Paul|  8224408|               44|  172|
| 577635693880635570| 13| 14|  3|  4|  4|  2|  1|  0|  0|  1|  1|  0|  1|  1|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|                 Tom|102597941|              115|  108|
+-------------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+--------------------+---------+-----------------+-----+
only showing top 20 rows

#Screenshot #4 -

Here I am converting the *'host_is_superhost'* column into a 'dummy variable' where it will be a binary (1,0) column simplified to *'superhost*'. Take a screenshot of the show() call of the dataframe before going into the transformation for the RandomForest model.

*Note: Again be mindful that transformations will take some computation time.*

In [43]:
from pyspark.ml.feature import StringIndexer
totalsDF = StringIndexer(
    inputCol='host_id',
    outputCol='superhost',
    handleInvalid='keep').fit(totalsDF).transform(totalsDF)

totalsDF.show(5, truncate=True)

+-------------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---------+---------+-----------------+-----+---------+
|         listing_id| -1|  0|  1|  2|  3|  4|  5|  6|  7|  8|  9| 10| 11| 12| 13| 14| 15| 16| 17| 18| 19| 20| 21| 22| 23| 24| 25| 26|host_name|  host_id|number_of_reviews|price|superhost|
+-------------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---------+---------+-----------------+-----+---------+
|           50675728|  8| 22|  4|  3|  2|  1|  0|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  1|  0|  0|  0|   Carrie| 87338185|              107|  166|    268.0|
| 744478255073405873| 12| 29|  7|  1|  2|  7|  2|  0|  2|  1|  0|  0|  1|  2|  2|  0|  1|  0|  1|  0|  0|  1|  1|  0|  0|  0|  0|  0|  Brandon| 87807117|              174|  318|    270.0|
|            9740033| 11|  5|  0|  0|  4|  0|  2|  0|  0|  3|  1|  0|  0|  3|  0|  0|  0|  0|  0|  0|  1|  2|  0|  1|  1|  0|  0|  0|     Nina| 49746531|               98|   44|     10.0|
|           45075319| 47| 59| 17|  8| 12|  7|  2|  5|  2|  4|  2|  7|  4|  3|  1|  0|  0|  0|  0|  1|  0|  1|  1|  0|  0|  0|  1|  0|     Luke|219957508|              509|  113|    124.0|
|1108037590849320235|  2|  2|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|Catherine| 39660084|               19|  117|    181.0|
+-------------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---------+---------+-----------------+-----+---------+
only showing top 5 rows

Here we are defining the independent variables that we are going to include into our RandomTreeClassifier model. You can decide to include additional variables from the listings.csv dataframe and build out a robust model but here I am only including the discovered topics from the text of the reviews.

*Note: This will relate to the number of topics that you have run in your model. Do not run this code blindly without adjusting the numbers to match your model*

In [44]:
# Code to print out column names. Copy and paste the topics to make the coding of required features faster
column_names = totalsDF.columns
print(column_names)

['listing_id', '-1', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', 'host_name', 'host_id', 'number_of_reviews', 'price', 'superhost']

Builds up a ML pipeline through feature engineering and then establishes a RandomForest Classifier model

In [45]:
required_features = ['-1', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14'] # Make sure that you adjust this code to the number of topics that you have

from pyspark.ml.feature import VectorAssembler
assembler = VectorAssembler(inputCols=required_features, outputCol='features')
transformed_data = assembler.transform(totalsDF)

In [46]:
(training_data, test_data) = transformed_data.randomSplit([0.8,0.2])

In [47]:
from pyspark.ml.classification import RandomForestClassifier
rf = RandomForestClassifier(labelCol='superhost',
                            featuresCol='features',
                            maxDepth=5)

ON a large dataset be prepared for this to take awhile to run or to time out in our Google Colab notebook

In [48]:
model = rf.fit(training_data)

In [49]:
predictions = model.transform(test_data)

In [50]:
# Evaluate our model
from pyspark.ml.evaluation import MulticlassClassificationEvaluator
evaluator = MulticlassClassificationEvaluator(
    labelCol='superhost',
    predictionCol='prediction',
    metricName='accuracy')

#Screenshot  #5 -
This is the printout of the accuracy of the model predicting whether or not the airbnb host is a superhost. Take a screenshot of the printout cell of your models test accuracy. Though this is not the end all, be all for evaluating a RandomForest Classifier, it is a helpful measure in seeing how useful your model is making a prediction.

A next step is to look at the importance of features in the model when assisting the classification model. This can be an important component of our interpretation if we can look at different factors that really influence the predictions that we are making.

In [51]:
accuracy = evaluator.evaluate(predictions)
print('Test Accuracy = ', accuracy)

import pandas as pd
featureImp = pd.DataFrame(
list(zip(assembler.getInputCols(), model.featureImportances)),columns=["features", "importance"])
featureImp.sort_values(by="importance", ascending=False)

Test Accuracy =  0.06451612903225806

   features  importance
1         0    0.151979
0        -1    0.144171
2         1    0.068934
10        9    0.068827
4         3    0.065086
7         6    0.060477
6         5    0.059197
5         4    0.059173
14       13    0.058920
3         2    0.056358
12       11    0.048261
9         8    0.042793
11       10    0.036070
8         7    0.027809
13       12    0.026480
15       14    0.025465

`topic_model.get_topic_info()`

Command allows us to see the main components of our topic modeling on the dataset and provides a representive document for each topic.

In [52]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,5249,-1_enjoyed_loved_stayed_cozy,"[enjoyed, loved, stayed, cozy, needed, town, t...",[Lark was very flexible and friendly. She was...
1,0,5768,0_coffee_kitchen_airbnb_loved,"[coffee, kitchen, airbnb, loved, walk, family,...",[This was our very first Airbnb reservation. ...
2,1,1299,1_helpful_responsive_host_communication,"[helpful, responsive, host, communication, acc...",[Such an amazing place to stay! Super clean an...
3,2,1218,2_distance_walkable_walking_quiet,"[distance, walkable, walking, quiet, restauran...",[This place is perfect for your Bozeman stay! ...
4,3,891,3_communication_convenient_exactly_good,"[communication, convenient, exactly, good, exc...","[Beautiful spot! Comfortable, clean and cute.,..."
5,4,722,4_montana_yellowstone_ski_state,"[montana, yellowstone, ski, state, skiing, sky...",[What a wonderful Airbnb!!<br/>Super cute and ...
6,5,511,5_basement_bedroom_noise_shower,"[basement, bedroom, noise, shower, bathroom, u...",[Exceptionally clean with great amenities! Com...
7,6,389,6_heart_weekend_base_visiting,"[heart, weekend, base, visiting, spot, getaway...",[I would absolutely stay in this little gem ag...
8,7,331,7_enjoyed_good_vey_thanks,"[enjoyed, good, vey, thanks, thank, wonderful,...","[Nice place, good location, had a really good ..."
9,8,312,8_brilliant_spot_good_awesome,"[brilliant, spot, good, awesome, advertised, t...","[great spot, as advertised!, Great spot. As a..."
10,9,283,9_uncomfortable_did_sleep_loud,"[uncomfortable, did, sleep, loud, night, dirty...",[worst host experience ever. 0 stars . worst ...
11,10,268,10_second_definitely_repeat_book,"[second, definitely, repeat, book, come, forwa...",[A repeat stay for us and the place was just a...
12,11,235,11_beds_bed_comfy_shower,"[beds, bed, comfy, shower, sleep, bathroom, pi...","[This spot is cute and cozy - great linens, co..."
13,12,197,12_hosts_host_accommodating_awesome,"[hosts, host, accommodating, awesome, staff, a...",[Everything was great and exactly as described...
14,13,153,13_house_beautiful_home_comforts,"[house, beautiful, home, comforts, yard, apart...",[Beautiful home. Very comfortable and a wonder...
15,14,123,14_dog_dogs_joe_yard,"[dog, dogs, joe, yard, fenced, huck, hilary, p...","[Great spot, the fenced backyard was great for..."
16,15,121,15_kitchen_meals_cooking_cook,"[kitchen, meals, cooking, cook, stocked, equip...",[The house is awesome! Great location - conven...
17,16,110,16_near_close_right_main,"[near, close, right, main, stadium, downtown, ...",[Great place right near the heart of downtown!...
18,17,108,17_一切都很完美_设施非常全_虽然是地下室_生活配套设施齐全,"[一切都很完美, 设施非常全, 虽然是地下室, 生活配套设施齐全, 洗衣机好像不太好用, 有...","[房间是地下室，价格比较实惠，如果临时住一天还不错🤓，房间很干净，洗衣机好像不太好用, 房间..."
19,18,88,18_quiet_comunucation_whit_accuracy,"[quiet, comunucation, whit, accuracy, reflecti...","[Clean, quiet, comfortable and a great locatio..."
20,19,81,19_second_2nd_time_year,"[second, 2nd, time, year, love, staying, tear,...",[This was the second time we have stayed at Br...
21,20,75,20_hostel_soon_rent_come,"[hostel, soon, rent, come, exists, slay, ll, b...","[Amazingly amazing hostel & great people!, Lov..."
22,21,54,21_ve_airbnb_best_favorite,"[ve, airbnb, best, favorite, stayed, airbnbs, ...",[Hands down the best Airbnb space I’ve been to...
23,22,51,22_muy_la_el_es,"[muy, la, el, es, sehr, und, war, wir, en, que]",[Fue una estancia muy corta pero sin duda volv...
24,23,50,23_na_gg_aa_hostile,"[na, gg, aa, hostile, אהבנו, xxx, ggg, ndnedjj...","[Use my previous comments, Na, na]"
25,24,38,24_couldn_asked_bro_staycationing,"[couldn, asked, bro, staycationing, masks, cus...",[We couldn’t have asked for better people to r...
26,25,26,25_longer_wish_stayed_trendiest,"[longer, wish, stayed, trendiest, sto, everthi...",[We really enjoyed staying here and wish we co...
27,26,25,26_ski_skiing_bridger_bowl,"[ski, skiing, bridger, bowl, convene, vacay, c...",[Great! Very responsive host. Place was close ...

## Screenshot #6
BONUS - Go through some of the John Snow Labs documentation and tutorials (https://nlp.johnsnowlabs.com/models?type=pipeline) and https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/tutorials/Certification_Trainings/Public


And apply a new technique to our dataset. You will have to write your own code here. You do not need a new dataset (not another city download) but a new analytics applied to the same dataset that you already have preloaded.

In [54]:
# SCREENSHOT 6 - Basic text classification with MLlib

from pyspark.ml.feature import Tokenizer, HashingTF, IDF
from pyspark.ml.classification import LogisticRegression
from pyspark.ml import Pipeline

# Creating a dummy sentiment label (1 for long reviews, 0 for short)
reviews_labeled = review_text.withColumn(
    "label",
    (F.length(F.col("comments")) > 100).cast("integer")
)

# Tokenize and transform text
tokenizer = Tokenizer(inputCol="comments", outputCol="words")
hashingTF = HashingTF(inputCol="words", outputCol="rawFeatures", numFeatures=1000)
idf = IDF(inputCol="rawFeatures", outputCol="features")
lr = LogisticRegression(maxIter=10)

pipeline = Pipeline(stages=[tokenizer, hashingTF, idf, lr])

model = pipeline.fit(reviews_labeled)

predictions = model.transform(reviews_labeled)

predictions.select("comments", "label", "prediction").show(5, truncate=False)

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+----------+
|comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |label|prediction|
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+----------+
|Brian was an awesome host! The apartment was recently remodeled and definitely felt like a new home. I'd definitely stay here again. I love his place!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |1    |1.0       |
|Brian was the absolute, best host.  If we needed anything he provided it. His studio is very sweet too.  The nine windows on three walls makes it feel very spacious.  It is decorated very tastefully.  Highly recommended!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |1    |1.0       |
|great place! great view! easy to walk to everything! great, friendly, easy-to-communicate-with host! totally awesome dogs! i hope to be moving to bozeman, but if not and i'm just visiting i'd definitely want to stay there again. thanks, brian, for making it so easy!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |1    |1.0       |
|My fiance and I had an absolutely amazing time staying at Brian's place in Bozeman!  The place is very clean, modern, and extremely comfortable!  We arrived to a bottle of wine, beer and water in the fridge, and warm coffee and tea any time we wanted it.  Brian was very friendly, welcoming, laid back, and helpful!  I cannot say enough good things about our stay here.  I think the number one way you can truly show how much you enjoyed a place is by using the same place to stay when you return to that city...and that is exactly what we'll be doing anytime we come to Bozeman!  We had plenty of privacy, and if we needed anything at all Brian was only a text or phone call away.  I HIGHLY RECOMMEND staying at this beautiful loft right next to downtown Bozeman.|1    |1.0       |
|Brian was a a fantastic host. He was helpful with providing advice for places to go around town. The room was well equipped and exceptionally well put together. Would definitely stay here again.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |1    |1.0       |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+----------+
only showing top 5 rows

Basic text classification with MLlib::This​‍​‌‍​‍‌ program accepts review comments and categorizes them automatically by initially splitting the text into words and changing those words into numerical features with the help of HashingTF and IDF. A Logistic Regression model is fitted with a straightforward rule-based label (long reviews = 1, short reviews = 0) to get the idea of the patterns in the text. The pipeline is a complete processing unit that takes the data as input and gives the output in the form of predictions indicating the model's classification of each comment on the basis of its acquired comprehension of the ​‍​‌‍​‍‌text.